### ISSUE TITLE
Installation guide missing. Firejail parameters needed.

### ISSUE THREAD

**Issue by bruceleerabbit** [wireapp/kalium#1230]
The `README.md` file is missing the installation procedure for Debian users. So in an effort to guess on how to securely install Kalium, I ran this (with an HTTP proxy on port 8118):
```
$ cd /usr/local/src
$ sudo git clone --config http.proxy=http://127.0.0.1:8118 https://github.com/wireapp/kalium.git
```
Then in attempt to run it securely, I essentially ran:
```
$ firejail /usr/local/src/kalium/gradlew jvmTest
```
The output was:
```
Downloading https://services.gradle.org/distributions/gradle-7.5.1-all.zip
```
I killed it immediately because obviously it’s trying to self-install missing components like _gradle_. Which components should be installed system-wide as root? It’s unclear if it’s sensible for a user to install gradle. What’s the target path for Gradle?  Running in firejail means that wherever the target path is for gradle, it will not persist unless firejail whitelists that path.  So since Kalium is partially self-installing, Firejail users need to know (prior to installation) which paths Kalium needs access to.

I suspect Debian users need to run this prior to running `gradlew` for the first time:
```
$ sudo aptitude install gradle libsodium23 -r
```
Indeed that seems to promote more progress. The script no longer attempts to download Gradle thereafter. But Debian has no pkg names containing “cryptobox”, so it’s unclear how to satisfy those dependencies in advance. (edit: I just noticed they are in-house projects which depend on rust. Debian has over 26000 pkgs related to rust, so we need to know which ones are needed by the cryptobox libs [just `rustc` perhaps?]). 

We also need to know prior to running an installed copy which paths Kalium needs at runtime in a normal chat session. It appears `~/.gradle/` is needed, so I created that and ran:
```
$ firejail --whitelist=$HOME/.gradle /usr/local/src/kalium/gradlew jvmTest
```
This gives:
```
Exception in thread "main" java.lang.RuntimeException: Could not create parent directory for lock file /home/user/.gradle/wrapper/dists/gradle-7.5.1-all/1ehga6e77gqps5uk2kc5kf1vc/gradle-7.5.1-all.zip.lck
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:43)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```
Why is the gradle zip file still in play?

**Comment by vitorhugods** [comment]
Hello hello,

It's perfectly normal that Gradle will download the exact version of Gradle specified in the [gradle-wrapper.properties](https://github.com/wireapp/kalium/blob/develop/gradle/wrapper/gradle-wrapper.properties) file if it is not yet installed in your machine.

More about it [here](https://docs.gradle.org/current/userguide/gradle_wrapper.html).

Gradle tries to solve the issue where some projects may require different versions of Gradle by doing this. Currently, we're using Gradle 7.5.1, so the Gradle Wrapper will download it if it's not the one in your machine.
This 7.5.1 version does NOT need to be installed system-wide, nor added to the PATH env variable.
At the end of the `Downloading https://services.gradle.org/distributions/gradle-7.5.1-all.zip`, the zip will be located at `~/.gradle/wrapper/dists` to be shared with other projects that you might attempt to run on your machine that may need the same Gradle version.

`./gradlew.sh` will then use this downloaded Gradle distribution to run the tasks. No installation needed.

> Which components should be installed system-wide as root? 

Technically... none that I can think of. It should be perfectly possible to have a local JDK inside the project and set that as `JAVA_HOME` before running `gradlew` commands. Same for the other dependencies mentioned in the [README](https://github.com/wireapp/kalium#running-the-cli): `libsodium`, `cryptobox-c` and `cryptobox4j`.

Even though JDK11 and `libsodium` can be installed more traditionally with the Linux package manager of choice, `cryptobox-c` and `cryptobox4j` are a bit more annoying. We have the plans to stop using Cryptobox completely and bundling `libsodium` inside Kalium to completely remove these dependencies, as [core-crypto](https://github.com/wireapp/core-crypto) will bridge between an implementation of Proteus (what Cryptobox currently does) and the new [MLS protocol](https://messaginglayersecurity.rocks/).

**Comment by bruceleerabbit** [comment]
Thanks for the feedback!

I reversed the Gradle installation:
```
$ sudo aptitude remove gradle
$ rm -rf ~/.gradle
```
Then ran:
```
$ firejail /usr/local/src/kalium/gradlew jvmTest
```
Output:
```
Downloading https://services.gradle.org/distributions/gradle-7.5.1-all.zip
...............10%................20%................30%................40%................50%................60%...............70%................80%................90%................100%

Welcome to Gradle 7.5.1!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

For more details see https://docs.gradle.org/7.5.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Directory '/home/user' does not contain a Gradle build.

A Gradle build should contain a 'settings.gradle' or 'settings.gradle.kts' file in its root directory. It may also contain a 'build.gradle' or 'build.gradle.kts' file.

To create a new Gradle build in this directory run 'gradlew init'
```
Is that error normal?  This came up empty:
```
find .gradle/ \( -iname settings.gradle\* -o -iname build.gradle\* \)
```
So I ran:
```
firejail --noblacklist=$HOME/.gradle /usr/local/src/kalium/gradlew init
```
which stops at this prompt:
```
Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 
```
What’s the correct answer here?

**Comment by tmspzz** [comment]
@bruceleerabbit thanks for opening an issue. 

I don't believe so far we tried to setup or run the project on Debian. We would be happy to add your instructions if you figure out how to do it. However, for the time being this is not something we'll actively look into or maintain ourselves.

**Comment by bruceleerabbit** [comment]
I noticed that if the first step is something like:
```
git clone https://github.com/wireapp/kalium.git ~/packages/
```
the installation that follows makes far more progress than if the first step is:
```
sudo git clone https://github.com/wireapp/kalium.git /usr/local/src/
```
Thus, the installation is fragile or broken when making Kalium available systemwide.

There’s still an issue with the installation instructions. For a *user* install (when the user has write access to the installation directory), it eventually dies with:
```
> Task :cryptography:compileKotlinJvm FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cryptography:compileKotlinJvm'.
> Error while evaluating property 'filteredArgumentsMap' of task ':cryptography:compileKotlinJvm'
   > Could not resolve all files for configuration ':cryptography:jvmCompileClasspath'.
      > Could not resolve com.wire:core-crypto-jvm:0.6.0-pre.4.
        Required by:
            project :cryptography
         > Could not resolve com.wire:core-crypto-jvm:0.6.0-pre.4.
            > Could not get resource 'https://maven.pkg.github.com/wireapp/core-crypto/com/wire/core-crypto-jvm/0.6.0-pre.4/core-crypto-jvm-0.6.0-pre.4.pom'.
               > Username must not be null!
```
I suspect this is related to not having a `local.properties` file.  The first step says a username and token goes in that file, but it does not say where that file is expected to be. I ran this and it came up empty:
```
find ~/packages/kalium ~/.gradle -name local.properties
```
Even after the installation dies, the `local.properties` file still does not exist.

**Comment by tmspzz** [comment]
Closing. Feel free to pick up again.
