### ISSUE TITLE
Add proxy support (with Tor in mind)

### ISSUE THREAD

**Issue by bruceleerabbit** [wireapp/kalium#1233]
Wire is a security-focused app and a signficant portion of users demand & expect privacy. Users prefer not to trust any 3rd party more than necessary. Yet the core service is Amazon AWS hosted and there are [many proven reasons](https://git.disroot.org/cyberMonk/liberethos_paradigm/src/branch/master/rap_sheets/amazon.md) to distrust Amazon. Some components [must be fetched](https://github.com/wireapp/kalium/issues/1231) from Microsoft (which also has [trust issues](https://git.sdf.org/humanacollaborator/humanacollabora/src/branch/master/github.md)). So Tor support is paramount.

The enterprise users may not be interested in Tor, but companies often have HTTP proxies & egress firewalls to enforce them. So HTTP proxies should be supported in general to accommodate both corporate users & privacy enthusiasts.

Since Kalium is a java app, the `torsocks` hack is not an option. There needs to be an HTTP proxy parameter. And if users supply an HTTP proxy URL, they should have confidence that every executable uses it (incl. cURL, wget, java, etc).

**Workaround**

The only workaround in the absence of HTTP proxy support is sandboxing the app with something like *Firejail* or a VM like *Virtualbox*. But because Kalium is distributed as a monolithic self-installing script, this greatly complicates using Firejail.

**Comment by tmspzz** [comment]
> Since Kalium is a java app

I think there is a mismatched expectation here. 


Kalium **is not supposed to be a stand alone java application**, but rather a library with which you can build applications.

It just so happens there is `CLI` module that runs some of the functionality the library provides.

**Comment by tmspzz** [comment]
Closing. Feel free to pick up again.
