### ISSUE TITLE
Add Firejail support

### ISSUE THREAD

**Issue by bruceleerabbit** [wireapp/kalium#1234]
Firejail is a sandbox that gives users some basic confidence that an untrusted app is not snooping on the local system (e.g. filesystem) without having to do a code inspection. It also gives users some control over an app’s access to network space.

Apps sometimes support network proxies (such as the suggestion in bug #1233), but that’s merely a user preference. Apps can (and sometimes do) ignore user specified proxies, in which case users still must trust the app to use the proxy. Firejail definitively enforces the users’ access expectations.

Supporting Firejail does not require any code changes. It entails creating a profile that specifies files and resources that Kalium needs. Since Kalium is self-installing, there should be two profiles: one for installation and one for normal runs after installation.

A comment requesting the same has been [mirrored](https://github.com/netblue30/firejail/issues/1139#issuecomment-1350342973) to the Firejail project.

When the Firejail profile is complete, it’s useful even to non-Firejail users because it shows users what directories & accesses are needed. In the absence of a profile, the installation docs should show which Firejail commandline options are needed for each command.

BTW, it’s worth noting that a Firejail profile [already exists for Wire](https://github.com/netblue30/firejail/issues/1139#issuecomment-293617990).

**Comment by tmspzz** [comment]
Closing. Feel free to pick up again.
